import React, {useEffect} from "react";
import styles from "../styles/Habilidades.module.css";
import Layout from "../Components/Layout";
import Image from "next/image";
import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { getHabilidades } from "../Redux/actions";

export default function Skills() {
  const dispatch = useDispatch()
  const habilidades = useSelector(state => state.habilidades)

  useEffect(()=>{
    dispatch(getHabilidades())
  }, [])



  return (
    <div>
       
      <div className={styles.Habilidades__container}>
        <Head>
          <title>Julio Humere</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/img/inicio.ico" />
        </Head>
        <Layout />
            <div className={styles.Habilidades__div}>
              {habilidades && habilidades.map(e=>(
              <div key={e} className={styles.Habilidades__tecnologia}>
                <Image src={e.icono} width='50' height='50' />
                <h5>{e.tecnologia}</h5>
              </div>
            ))}
            </div>   
      </div>
    </div>
  );
}