import React, {useEffect} from "react";
import styles from "../styles/Habilidades.module.css";
import Layout from "../Components/Layout";
import Image from "next/image";
import Head from "next/head";
import HabilidadesJSON from "../JSON/Habilidades.json";
import { useSelector, useDispatch } from "react-redux";
import { getHabilidades } from "../Redux/actions";

export default function Skills(props) {
  const dispatch = useDispatch()
  const habilidades = useSelector(state => state.habilidades)

  useEffect(()=>{
    dispatch(getHabilidades())
  }, [])


  return (
    <div>
       
      <div className={styles.Habilidades__container}>
        <Head>
          <title>Julio Humere</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/img/inicio.ico" />
        </Head>\
        <Layout />
            {/* <div className={styles.Habilidades__title}>
              <h1>{props.Habilidades.Titulo}</h1>
              <h4>{props.Habilidades.Info}</h4>
            </div> */}
            <div className={styles.Habilidades__div}>
              {habilidades.Habilidades && habilidades.Habilidades.map(e=>(
              <div key={e} className={styles.Habilidades__tecnologia}>
                <Image src={e.icono} width='50' height='50' />
                <h5>{e.tecnologia}</h5>
              </div>
            ))}
            </div>   
      </div>
    </div>
  );
}

export async function getStaticProps({ locale }) {
  const response = await import(`../Lenguajes/${locale}.json`);
  return {
    props: {
      Habilidades: response.default.Habilidades,
    },
  };
}
