import Typewriter from "typewriter-effect";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "../Components/Layout";
import { motion } from "framer-motion";

import { SocialIcon } from "react-social-icons";

export default function Home(props) {
  return (
    <motion.div
      className="box"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <div className={styles.home__container}>
        <Head>
          <title>Julio Humere</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/img/inicio.ico" />
        </Head>
        <Layout />
        <div className={styles.home__divMayor}>
          <h1 className={styles.home__title}>Julio Humere</h1>
          <Typewriter
            options={{
              loop: true,
              autoStart: true,
              pause: 3000,
              strings: [`${props.index.Descripcion}`],
            }}
          />

          <ul className={styles.home__ul}>
            <li>
              <SocialIcon
                network="github"
                bgColor="white"
                url="https://github.com/Julihumere"
                target={"_blank"}
              />
            </li>
            <li>
              <SocialIcon
                network="linkedin"
                bgColor="white"
                url="https://www.linkedin.com/in/juli-humere/"
                target={"_blank"}
              />
            </li>
            <li>
              <SocialIcon
                network="whatsapp"
                bgColor="white"
                url="https://walink.co/ef4aa4"
                target={"_blank"}
              />
            </li>
          </ul>
        </div>
      </div>
    </motion.div>
  );
}

export async function getStaticProps({ locale }) {
  const response = await import(`../Lenguajes/${locale}.json`);
  return {
    props: {
      index: response.default.index,
    },
  };
}
