import Typewriter from "typewriter-effect";
import Head from "next/head";
import styles from "../styles/Index.module.css";
import { SocialIcon } from "react-social-icons";
import { useRouter } from "next/router";
import Link from "next/link";
import Lenguajes from "../Components/Lenguajes";


export default function Home(props) {
    const router = useRouter()
    const idioma = router.locale
    
  return (
 
        <div className={styles.index__container}>
    <Head>
        <title>Julio Humere</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/inicio.ico" />
      </Head>
      
      <div className={styles.index__divMayor}>

        <div className={styles.index__divTitle}>
            <h1>{props.index.Titulo}</h1>           
           <div className={styles.lenguajes}><Lenguajes /></div>
        </div>
      
        <div className={styles.divTypewriter}>
          <h2 className={styles.typewriter}>
          <Typewriter
          options={{
            loop: true,
            autoStart: true,
            strings: [`${props.index.Fullstack}`,`${props.index.Frontend}`,`${props.index.Backend}`],
          }}
        />
        </h2>
        </div>
  
        
   
        
          <div className={styles.index__buttons}>
          <Link href={"/SobreMi"}>
              <button className={styles.Index__button}>
                {idioma === "es" ? <span>Sobre Mi</span> : <span>About</span>}
              </button>
            </Link>
            <Link href={"/Habilidades"}>
              <button className={styles.Index__button}>
                {idioma === "es" ? <span >Habilidades</span> : <span>Skills</span>}
              </button>
            </Link>
            <Link href={"/Proyectos"}>
              <button className={styles.Index__button}>
                {idioma === "es" ? <span >Proyectos</span> : <span>Projects</span>}
              </button>
            </Link>
            </div>
     

            <ul className={styles.index__ul}>
          <li>
            <SocialIcon
              network="github"
              bgColor="black"
              fgColor="white"
              url="https://github.com/Julihumere"
              target={"_blank"}
            />
          </li>
          <li>
            <SocialIcon
              network="linkedin"
              bgColor="black"
              fgColor="white"
              url="https://www.linkedin.com/in/juli-humere/"
              target={"_blank"}
            />
          </li>
          <li>
            <SocialIcon
              network="whatsapp"
              bgColor="black"
              fgColor="white"
              url="https://walink.co/ef4aa4"
              target={"_blank"}
            />
          </li>
        </ul>

          </div>

        
    
    </div>
  );
}

export async function getStaticProps({ locale }) {
  const response = await import(`../Lenguajes/${locale}.json`);
  return {
    props: {
      index: response.default.index,
    },
  };
}
