import React, { useRef, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import styles from "../styles/Proyectos.module.css";
import Layout from "../Components/Layout";
import Head from "next/head";
import SlideShow from "../Components/SlideShow";
import {AiFillStar} from "react-icons/ai"
import {BsFillJournalBookmarkFill} from 'react-icons/bs'
import {FaGraduationCap} from 'react-icons/fa'
import { getProyectos } from '../Redux/actions.js'


export default function Projects(props) {
  const dispatch = useDispatch()
  const algo = useSelector(state=> state.proyectos)
  console.log(algo)


  useEffect(()=>{
    dispatch(getProyectos())
  },[])


  const proyectos = {
    proyectos: [
      {
        titulo: "Foodies",
        imagen: "/img/Proyectos/Foods (1).png",
        video: "/img/Proyectos/Foodies.mp4",
        info: `${props.Proyectos.TextoFoodies}`,
        tecnologias: [
          "React",
          "Redux",
          "NodeJs",
          "ExpressJs",
          "Sequelize",
          "SQL",
          "Vercel",
          "Heroku",
        ],
        href: 'foodies'
      },
      {
        titulo: "Love of Travel",
        imagen: "/img/Proyectos/love of travel (1).png",
        video: "/img/Proyectos/Love of Travel.mp4",
        info: `${props.Proyectos.TextoTravel}`,
        tecnologias: [
          "React",
          "Redux",
          "NodeJs",
          "ExpressJs",
          "Sequelize",
          "SQL",
          "Vercel",
          "Heroku",
        ],
        href: 'countries'
      },
      {
        titulo: "Pomodoro and ToDo",
        imagen:"/img/Proyectos/Pomodoro and ToDo - Brave 26_8_2022 14_38_17.png",
        video:"/img/Proyectos/Pomodoro and Todo.mp4",
        info: `${props.Proyectos.TextoPomodoro}`,
        tecnologias: ["NextJs", "Vercel", "Module.css"],
        href: 'pomodoroAndTodo'
      },
      {
        titulo: "Portafolio",
        imagen: "/img/Proyectos/Portfolio.png",
        video: "/img/Proyectos/Portfolio.mp4",
        info: `${props.Proyectos.TextoPortafolio}`,
        tecnologias: ["NextJs", "Vercel", "Module.css"],
        href: 'portfolio'
      },
    ],
    
    
    
  };



  return (
    <div>
        <Layout />
        <Head>
          <title>Julio Humere</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/img/inicio.ico" />
        </Head>
      
        <div className={styles.Proyectos__container}>

        
          <div className={styles.Proyectos__titulo__slideShow}>
            <h1>Explora los proyectos</h1>
          <h3>Haciendo click te desplazaras al detalle!</h3>
                 
          <div className={styles.SlideShow}>
            <SlideShow proyectos={proyectos} />
          </div>
          </div> 
          
         <div className ={styles.Proyectos__container__card}>
          {proyectos && proyectos.proyectos.map(e => 
          
         <div key={e.href} className ={styles.Proyectos__card} id={e.href}>
          <div className={styles.Proyectos__card__color}> </div>
            <div className={styles.Proyectos__info}>
              <p>01/01/0000</p>
              <h1><AiFillStar/>{e.titulo}</h1>
              <span className={styles.line}></span>
              <div className={styles.Proyectos__info__detail}><BsFillJournalBookmarkFill size='2em' /><h3>{e.info}</h3></div>
              <span className={styles.line}></span>
              <div className={styles.Proyectos__info__education}><FaGraduationCap  size='3em'/><h4>Henry</h4></div>
            </div>
            <div className={styles.Proyectos__img}>
              <video controls width={"600"} height={"400"} style={{borderRadius: "25px"}} >
                <source src={e.video} />
              </video>
              <span className={styles.line}></span>
              <div className={styles.tenchnologies}>{e.tecnologias.map((e)=> (<h4 key={e}>{e}</h4>))}</div>
            </div>
         </div>
        
           )}
           
         </div>
         
        </div>      
    </div>
  );
}

export async function getStaticProps({ locale }) {
  const response = await import(`../Lenguajes/${locale}.json`);
  return {
    props: {
      Proyectos: response.default.Proyectos,
    },
  };
}
